language: python
cache: pip
python:
- '2.7'
- '3.7.9'
- '3.8'
- '3.9'
install:
- pip install -U pip
- pip uninstall -y six
- pip install six>=1.12.0
- if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then pip install --only-binary -e .; else
  pip install --prefer-binary -e .; fi
script: python setup.py test
before_install:
- openssl aes-256-cbc -K $encrypted_efe1688938da_key -iv $encrypted_efe1688938da_iv
  -in travis.secrets.tar.gz.enc -out travis.secrets.tar.gz -d
- tar xvzf travis.secrets.tar.gz
